ALTER TABLE memberships DROP COLUMN IF EXISTS position;
ALTER TABLE memberships DROP COLUMN IF EXISTS jersey_number;

ALTER TABLE teams DROP COLUMN IF EXISTS is_active;
ALTER TABLE teams DROP COLUMN IF EXISTS currency;
ALTER TABLE teams DROP COLUMN IF EXISTS fee_due_day;
ALTER TABLE teams DROP COLUMN IF EXISTS fee_amount;
ALTER TABLE teams DROP COLUMN IF EXISTS logo_url;
ALTER TABLE teams DROP COLUMN IF EXISTS category;
ALTER TABLE teams DROP COLUMN IF EXISTS club_id;
ALTER TABLE teams DROP COLUMN IF EXISTS sport_id;

ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS phone;
