ALTER TABLE users DROP COLUMN IF EXISTS bio;
ALTER TABLE users DROP COLUMN IF EXISTS dominant_side;
ALTER TABLE users DROP COLUMN IF EXISTS city;
ALTER TABLE users DROP COLUMN IF EXISTS alias;
ALTER TABLE users DROP COLUMN IF EXISTS birth_date;
ALTER TABLE users DROP COLUMN IF EXISTS weight_kg;
ALTER TABLE users DROP COLUMN IF EXISTS height_cm;
ALTER TABLE users DROP COLUMN IF EXISTS favorite_sport;
